"""
Controller.py  (version 3.0)

This module defines a Controller class that creates the connection between the Computer and the AWG.
It defineds helpful functions that convert arbitrary frequencies to the closest frequencies that can
be generated by the AWG, and it also defines a function to generate a multi-tone signal with the AWG.

The Controller also warns the user, if the user tries to generate tones that are incompatible with the 
AWG and also warns if power levels are too high for the number of tones generated, or if the on-chip DDS
command FIFO would overflow.

The Controller is written for the SPCM AWG M4i.6631-x8 cards and Windows OS.

@author: Bjarne Schümann
@date: 01.06.2026
"""

from typing import Literal
from pathlib import Path
from spcm import units
import numpy as np
import threading
import warnings
import psutil
import spcm
import time
import h5py
import os


p = psutil.Process(os.getpid())
p.nice(psutil.REALTIME_PRIORITY_CLASS)
card : spcm.Card

def convert_position_to_freq(position_arr: np.ndarray,
                             f_start_hz: float = 100e6,
                             um_per_MHz: float = 4.6 / 0.6) -> np.ndarray:
    position_arr = np.asarray(position_arr, dtype=float)
    if position_arr.ndim == 1:
        position_arr = position_arr[np.newaxis, :]
    if np.all(position_arr[:, 0] == 0):
        warnings.warn(
        "position_arr[:, 0] should be 0 to align with f_start_hz reference. " \
        "Be aware that nonzero initial positions will be treated as offsets"
    )
    return f_start_hz + (position_arr / um_per_MHz) * 1e6

def load_control_protocol(
    path: Path,
    w0_um: float | None = None,
) -> tuple[np.ndarray, np.ndarray, np.ndarray | None, np.ndarray]:
    with h5py.File(path, "r") as f:
        atr = f.attrs

        if "t_us" in f:
            t_us = np.asarray(f["t_us"])
        elif "t_ms" in f:
            t_us = np.asarray(f["t_ms"]) * 1000.0
        else:
            raise ValueError(f"No time dataset ('t_us' or 't_ms') found in {path}")

        _w0 = w0_um if w0_um is not None else (float(atr["w0_um"]) if "w0_um" in atr else None) # type:ignore

        if "ux_um" in f:
            ux_um = np.asarray(f["ux_um"])
        elif "ux" in f:
            if _w0 is None:
                raise ValueError(
                    f"{path} has no 'ux_um' dataset and no 'w0_um' attribute; "
                    "pass w0_um explicitly to convert dimensionless 'ux'."
                )
            ux_um = np.asarray(f["ux"]) * _w0
        else:
            raise ValueError(f"No ux dataset ('ux_um' or 'ux') found in {path}")

        if "uy_um" in f:
            uy_um: np.ndarray | None = np.asarray(f["uy_um"])
        elif "uy" in f:
            if _w0 is None:
                raise ValueError(
                    f"{path} has no 'uy_um' dataset and no 'w0_um' attribute; "
                    "pass w0_um explicitly to convert dimensionless 'uy'."
                )
            uy_um = np.asarray(f["uy"]) * _w0
        else:
            uy_um = None

        ua = np.asarray(f["ua"])

    return t_us, ux_um, uy_um, ua

def arc_length_spacing(position_arr: np.ndarray, time_arr:np.ndarray, n_points: int) -> tuple[np.ndarray, np.ndarray]:
    """
    This function takes in a 1D array of the position array of a very high resolution with e.g. equally spaced time points.
    The return is then the new position array with n_points equally spaced in arc length along the trajectory and 
    the corresponding time array.
    """
    position_arr = np.asarray(position_arr, dtype=float)
    time_arr = np.asarray(time_arr, dtype=float)
    if position_arr.ndim != 1 or time_arr.ndim != 1:
        raise ValueError("position_arr and time_arr must be 1D.")
    if position_arr.shape[0] != time_arr.shape[0]:
        raise ValueError("position_arr and time_arr must have the same length.")
    if n_points < 2:
        raise ValueError("n_points must be at least 2.")

    t_scale = time_arr[-1] - time_arr[0]
    x_scale = np.ptp(position_arr)
    if x_scale == 0:
        x_scale = t_scale
    dt = np.diff(time_arr) / t_scale
    dx = np.diff(position_arr) / x_scale
    s = np.concatenate([[0], np.cumsum(np.sqrt(dt**2 + dx**2))])
    s_new = np.linspace(0, s[-1], n_points)
    position_new = np.interp(s_new, s, position_arr)
    time_new = np.interp(s_new, s, time_arr)
    return position_new, time_new

def resample_curvature_weighted(x, t, n_points=30, alpha=None, normalize=True):
    """
    Curvature-weighted resampling of one or more 1-D time series.
    https://github.com/bayertom/sampling/blob/main/README.md

    We should normalize since the curvature formula is scale sensitive, but
    one can also try without normalization and tune alpha a bit.

    Returns
    -------
    x_new : ndarray, shape (n_points,) or (K, n_points)
    t_new : ndarray, shape (n_points,) or (K, n_points)
        For (K, T) input, each row has its own sample times, since each series
        is resampled according to its own shape.
    """
    x = np.asarray(x, float)
    t = np.asarray(t, float)

    squeeze = x.ndim == 1
    if squeeze:
        x = x[None, :]                       # (1, T)
    if x.ndim != 2:
        raise ValueError("x must have shape (T,) or (K, T)")
    if t.ndim != 1:
        raise ValueError("t must be 1-D")
    if x.shape[1] != t.shape[0]:
        raise ValueError("each series must have the same length as t")

    K = x.shape[0]
    x_new = np.empty((K, n_points))
    t_new = np.empty((K, n_points))
    for k in range(K):
        x_new[k], t_new[k] = _resample_one(x[k], t, n_points, alpha, normalize)

    if squeeze:
        return x_new[0], t_new[0]
    return x_new, t_new

def _resample_one(xk, t, n_points, alpha, normalize):
    """Resample a single 1-D series xk(t) by curvature-weighted arc length."""
    if normalize:
        x_span = np.ptp(xk) or 1.0
        t_span = np.ptp(t) or 1.0
        coords = np.column_stack([t / t_span, xk / x_span])
    else:
        coords = np.column_stack([t, xk])

    seg = np.linalg.norm(np.diff(coords, axis=0), axis=1)
    s = np.concatenate([[0.0], np.cumsum(seg)])

    A, B, C = coords[:-2], coords[1:-1], coords[2:]
    ab = np.linalg.norm(B - A, axis=1)
    bc = np.linalg.norm(C - B, axis=1)
    ca = np.linalg.norm(A - C, axis=1)

    d1 = B - A
    d2 = C - A
    area2 = np.abs(d1[:, 0] * d2[:, 1] - d1[:, 1] * d2[:, 0])

    denom = ab * bc * ca
    kappa_inner = np.where(denom > 0, 2 * area2 / np.maximum(denom, 1e-30), 0.0)
    kappa = np.concatenate([[0.0], kappa_inner, [0.0]])

    if alpha is None:
        alpha_k = np.median(seg) if seg.size else 0.0
    else:
        alpha_k = alpha
    w = 1.0 + alpha_k * kappa
    w_seg = 0.5 * (w[:-1] + w[1:]) * seg
    sigma = np.concatenate([[0.0], np.cumsum(w_seg)])

    if sigma[-1] <= 0:
        s_new = np.linspace(0.0, s[-1], n_points)
    else:
        sigma_new = np.linspace(0.0, sigma[-1], n_points)
        s_new = np.interp(sigma_new, sigma, s)

    x_out = np.interp(s_new, s, xk)
    t_out = np.interp(s_new, s, t)
    return x_out, t_out

def uniform_sampling(x,t,npoints):
    s = np.linspace(0.0, 1.0, x.shape[0])
    s_new = np.linspace(0.0, 1.0, npoints)
    x_new = np.interp(s_new, s, x)
    t_new = np.interp(s_new, s, t)
    return x_new, t_new

class AWGController:

    SAMPLE_RATE_HZ        = 1_250_000_000      # 1.25 GS/s
    DDS_TIMER_MIN_NS      = 83.2
    DDS_CMD_RATE_MAX_HZ   = 10_000_000
    DDS_FREQ_NYQUIST_HZ   = 625_000_000
    INT16_FULLSCALE       = 32767
    ONBOARD_MEMORY_SAMP   = 2 * 1024 ** 3 // 2   # 2 GiSamples (16-bit)
    SINGLE_MODE_QUEUE_MAX = 4096                 # on-chip DDS command FIFO (single mode)
    DDS_CMD_SLOT_S       = 6.4e-9                # 6.4 ns per command (hardware exec rate)
    DMA_REFILL_S_PER_CMD = 1.0e-7                # 100 ns/cmd (10 MHz sustained DMA refill)

    # Default core-to-channel mappings for the M4i.6631-x8 (2 ch, 23 cores)
    CORE_MAP_20_1 = {0: list(range(0, 20)), 1: [20]}              # default after reset
    CORE_MAP_16_5 = {0: list(range(0, 16)), 1: list(range(16, 21))}

    def __init__(
        self,
        serial_number: int,
        max_channel_amp_v: float = -np.inf,
        max_total_amplitude: float = 1.0,
        f_min_hz: float = 70e6,             # minimum AOD freq
        f_max_hz: float = 130e6,            # maximum AOD freq
        f_start_hz: float = 100e6,         # AOD center freq
        um_per_MHz: float = 4.6/0.6,
        core_mapping: Literal["20/1", "16/5"] = "20/1",
        realtime_priority: bool = True,
    ) -> None:

        self.sn = serial_number
        self.mode = "dds"
        self.max_channel_amp_v = max_channel_amp_v
        self.max_total_amplitude = max_total_amplitude
        self.f_min_hz = f_min_hz
        self.f_max_hz = f_max_hz
        self.f_start_hz = f_start_hz
        self.um_per_MHz = um_per_MHz

        if core_mapping == "20/1":
            self.core_map = self.CORE_MAP_20_1
        elif core_mapping == "16/5":
            self.core_map = self.CORE_MAP_16_5
        else:
            raise ValueError("core_mapping must be either '20/1' or '16/5'.")
        self.core_mapping = core_mapping

        self.dds = None
        self.card = None
        self.channels = None
        self.data_transfer = None
        self._queue_max_actual = None

        self._stream_thread:   threading.Thread | None = None
        self._stop_event:      threading.Event  | None = None
        self._stream_freqs_kt:       np.ndarray | None = None
        self._stream_amps_kt:        np.ndarray | None = None
        self._stream_dt_arr:         np.ndarray | None = None
        self._stream_cores:                list | None = None
        self._stream_continuous:           bool        = False
        self._replay_mode_active:          bool        = False
        self._static_core_state:           dict        = {}   # channel → soft state from program_static

        if realtime_priority:
            if os.name != 'nt':
                raise OSError("This code is only compatible with Windows OS.")
            try:
                psutil.Process(os.getpid()).nice(psutil.REALTIME_PRIORITY_CLASS)
            except Exception as e:
                print(f"[AODController] could not raise priority: {e}")
        return

    def connect(self) -> None:
        if self.card is not None:
            warnings.warn(f"Already connected to a card: {self.card.product_name()} SN={self.card.sn()}. Skipping connection.\n")
            return

        try:
            self.card = spcm.Card(serial_number=self.sn)
            self.card.__enter__()
            print(f"[AODController] Connected: {self.card.product_name()} "
                  f"SN={self.card.sn()} mode={self.mode}\n")
        except Exception as e:
            print(f"[AODController] Connection failed: {e}\n")
            return

        self._setup_dds_mode()

        return

    def _common_setup(self):
        if self.card is None:
            raise RuntimeError("Card not connected.\n")

        self.channels = spcm.Channels(self.card)
        for ch in self.channels:
            ch.enable(True)
            ch.diff(False)  # False single-ended, True differential
            ch.output_load(50 * units.ohm)
            ch.amp(self.max_channel_amp_v * units.V)

        trig = spcm.Trigger(self.card)
        trig.or_mask(spcm.SPC_TMASK_EXT0)
        trig.ext0_mode(spcm.SPC_TM_POS)         # positive/rising edge
        trig.ext0_level0(0.5 * units.V)         # external trigger level is 0.5 V
        trig.ext0_coupling(spcm.COUPLING_DC)    # set DC coupling
        trig.termination(1)                     # 1: 50Ohm, 0: HIGHZ

    def _setup_dds_mode(self) -> None:
        if self.card is None:
            raise RuntimeError("Card not connected.\n")

        self.card.card_mode(spcm.SPC_REP_STD_DDS)
        self._common_setup()
        self.card.write_setup()
        self.dds = spcm.DDS(self.card, channels=self.channels)
        self.dds.reset()


        if self.core_mapping == "16/5":
            mask0 = sum(1 << i for i in self.core_map[0])
            mask1 = sum(1 << i for i in self.core_map[1])
            self.dds.cores_on_channel(0, mask0)
            self.dds.cores_on_channel(1, mask1)

        try:
            self._queue_max_actual = int(self.dds.queue_cmd_max())
            print(f"[AODController] DDS command FIFO capacity: {self._queue_max_actual} entries.\n")
        except Exception:
            warnings.warn(f"[AWGController] could not query DDS command queue capacity - assuming {self.SINGLE_MODE_QUEUE_MAX} entries. \n")
            self._queue_max_actual = self.SINGLE_MODE_QUEUE_MAX


        f_park = 0.5 * (self.f_min_hz + self.f_max_hz)
        for core in self.dds:
            core.amp(0)
            core.freq(f_park * units.Hz)

        self.dds.trg_src(spcm.SPCM_DDS_TRG_SRC_CARD)
        self.dds.exec_at_trg()
        self.dds.write_to_card()
        self.card.start(spcm.M2CMD_CARD_ENABLETRIGGER,
                        spcm.M2CMD_CARD_FORCETRIGGER)
        print(f"[AODController] DDS mode armed ({self.core_mapping} split), all cores quiet.\n")
        return

    def disconnect(self) -> None:
        if self.card is None:
            return
        try:
            self.stop()
        finally:
            self.card.__exit__()
            self.card = None
            self.channels = None
            self.dds = None
            self.data_transfer = None
        return

    def arm_buffer_replay(
        self,
        time_arr: np.ndarray,
        position_arr: np.ndarray,
        channel: int = 0,
        amplitudes=None,
        back_and_forth: bool = False,
        hold: float = 0.0,
        where_hold_insert: Literal["after_return", "before_return"] = "before_return",
    ) -> int:
        """
        Render the trajectory to raw int16 samples, load into card RAM, and arm
        SPC_REP_STD_SINGLERESTART so every EXT0 pulse replays the identical buffer.

        The DDS engine is bypassed entirely; every sample is pre-computed by
        _synthesize_multitone. After this call returns, no background thread runs
        and the card is fully autonomous.  Call stop_replay() to halt and return
        to DDS mode.

        Args:
            time_arr:          (T,) ndarray (s). Increasing waypoint times.
            position_arr:      (T,) or (K, T) ndarray (µm). Per-atom trajectory.
            channel:           0 (X-AOD) or 1 (Y-AOD).
            amplitudes:        None, scalar, (K,), or (K, T) ndarray. Tone fractions.
            back_and_forth:    Appends time-reversed position trajectory.
            hold:              (s). Appends a zero-slope segment at the end.
            where_hold_insert: Where to insert the hold relative to the return leg.

        Returns:
            n_samples: Number of per-channel samples loaded into card memory.
        """
        if self.card is None:
            raise RuntimeError("Card not connected. Call connect() first.\n")

        if self.max_channel_amp_v == -np.inf:
            warnings.warn(
                "[AWGController] max_channel_amp_v is 0. Set a maximum output voltage before doing ANYTHING to prevent hardware damage."
            )
            _s = input("Do you still want to proceed? (y/n): ").strip().lower()
            if _s != 'y':
                print("Abort.\n")
                return 0
            print(
                f"Proceeding with max_channel_amp_v = {self.max_channel_amp_v} [V]. Be careful!\n"
            )

        result = self.plan(
            time_arr, position_arr,
            channel=channel,
            amplitudes=amplitudes,
            back_and_forth=back_and_forth,
            hold=hold,
            where_hold_insert=where_hold_insert,
            skip_timing_check=True,
        )
        freqs_kt = result.freqs_kt
        amps_kt  = result.amps_kt
        time_arr = result.time_arr

        # Tear down any active DDS streaming state
        if self._stop_event is not None:
            self._stop_event.set()
        if self._stream_thread is not None:
            self._stream_thread.join(timeout=5.0)
        self._stream_thread   = None
        self._stop_event      = None
        self._stream_freqs_kt = None
        self._stream_amps_kt  = None
        self._stream_dt_arr   = None
        self._stream_cores    = None
        self.card.stop(spcm.M2CMD_CARD_STOP)

        buf      = self._synthesize_multitone(freqs_kt, amps_kt, time_arr, channel)
        n_samples = len(buf) // 2  # buf is 2-channel interleaved

        self.card.card_mode(spcm.SPC_REP_STD_SINGLERESTART)
        self.card.write_setup()

        self.data_transfer = spcm.DataTransfer(self.card)
        self.data_transfer.memory_size(n_samples * units.S)
        self.data_transfer.allocate_buffer(n_samples * units.S)
        self.data_transfer.loops(1)
        self.data_transfer.buffer[:] = buf
        self.data_transfer.start_buffer_transfer(spcm.M2CMD_DATA_STARTDMA, spcm.M2CMD_DATA_WAITDMA)

        self.card.start(spcm.M2CMD_CARD_ENABLETRIGGER)

        duration_us = (time_arr[-1] - time_arr[0]) * 1e6
        print(
            f"[AODController] Buffer replay armed: {n_samples} samples, "
            f"{duration_us:.2f} µs, CH{channel}, SPC_REP_STD_SINGLERESTART. "
            f"EXT0 retriggers.\n"
        )
        self._replay_mode_active = True
        return n_samples

    def stop_replay(self) -> None:
        """
        Halt buffer replay, release the DMA buffer, and restore DDS mode.
        After this call, normal move() calls work again without additional setup.
        """
        if self.card is None:
            return
        self.card.stop(spcm.M2CMD_CARD_STOP)
        self.data_transfer = None
        self._setup_dds_mode()
        self._replay_mode_active = False
        print("[AODController] Buffer replay stopped. DDS mode restored.\n")

    def _select_cores(self, channel: int, K: int) -> list:
        if channel not in (0, 1):
            raise ValueError("channel must be 0 or 1.")
        cores_avail = self.core_map[channel]
        if K > len(cores_avail):
            raise ValueError(
                f"Requested K={K} tones on CH{channel}, but only "
                f"{len(cores_avail)} cores available in '{self.core_mapping}' "
                f"mapping. Increase to '16/5' or split tones across channels."
            )
        return cores_avail[:K]
  
    def _estimate_n_commands(self, K: int, T: int) -> int:
        # initial state: 1 trg_src + K*(freq, amp, phase, freq_slope, amp_slope) + 1 exec
        n_init = 1 + 5 * K + 1
        # per segment: trg_timer + trg_src + K*(freq, amp, freq_slope, amp_slope) + exec
        n_seg = 2 + 4 * K + 1
        # final park: timer + trg_src + K*(freq, amp, freq_slope, amp_slope) + exec
        n_park = 2 + 4 * K + 1
        return n_init + (T - 1) * n_seg + n_park
  
    def _synthesize_multitone(
        self,
        freqs_kt: np.ndarray,
        amps_kt:  np.ndarray,
        time_arr: np.ndarray,
        channel:  int,
    ) -> np.ndarray:
        """
        Render K phase-continuous chirped tones with piecewise-linear amplitude
        ramps into a 2-channel interleaved int16 buffer.

        Args:
            freqs_kt: (K, T) ndarray (Hz). Frequency waypoints per tone.
            amps_kt:  (K, T) ndarray, unitless in [0, 1]. Amplitude waypoints.
            time_arr: (T,)   ndarray (s). Strictly increasing waypoint times.
            channel:  0 or 1. Which interleave slot to populate; the other is zero.

        Returns:
            out: (2 * n_samples,) int16 ndarray, interleaved [ch0, ch1, ch0, ch1, ...].
        """
        fs = self.SAMPLE_RATE_HZ
        K, T = freqs_kt.shape
        n_samples = int(round((time_arr[-1] - time_arr[0]) * fs))

        signal = np.zeros(n_samples, dtype=np.float64)
        phase  = np.zeros(K,         dtype=np.float64)

        for i in range(T - 1):
            n_a   = int(round((time_arr[i]     - time_arr[0]) * fs))
            n_b   = int(round((time_arr[i + 1] - time_arr[0]) * fs))
            seg_n = n_b - n_a
            if seg_n <= 0:
                continue
            tau = np.arange(seg_n, dtype=np.float64) / fs
            dt  = time_arr[i + 1] - time_arr[i]

            for k in range(K):
                f_a, f_b = freqs_kt[k, i], freqs_kt[k, i + 1]
                a_a, a_b = amps_kt[k, i],  amps_kt[k, i + 1]
                phi = phase[k] + 2 * np.pi * (f_a * tau + 0.5 * (f_b - f_a) * tau**2 / dt)
                amp = a_a + (a_b - a_a) * tau / dt
                signal[n_a:n_b] += amp * np.sin(phi)
                phase[k] = (phase[k] + 2 * np.pi * 0.5 * (f_a + f_b) * dt) % (2 * np.pi)

        np.clip(signal, -1.0, 1.0, out=signal)
        mono = (signal * self.INT16_FULLSCALE).astype(np.int16)

        out = np.zeros(n_samples * 2, dtype=np.int16)
        out[channel::2] = mono
        return out

    def _segment_time_floors(self, K: int) -> tuple[float, float, float]:
        n_cmd_seg = 3 + 4 * K   # trg_timer + trg_src + 4*K core writes + exec_at_trg
        timer_floor  = self.DDS_TIMER_MIN_NS * 1e-9
        exec_floor   = n_cmd_seg * self.DDS_CMD_SLOT_S
        stream_floor = n_cmd_seg * self.DMA_REFILL_S_PER_CMD
        return timer_floor, exec_floor, stream_floor

    def _check_segment_timing(self, dt: np.ndarray, K: int, streaming: bool) -> None:
        """
        Check that every segments dt respects the timing floor.
        """
        timer_floor, exec_floor, stream_floor = self._segment_time_floors(K)
        n_cmd_seg = 3 + 4 * K
        eps = 1e-12   # float-comparison slack


        bad = dt < timer_floor - eps
        if np.any(bad):
            worst = float(dt[bad].min())
            raise ValueError(
                f"[timing] {int(bad.sum())}/{dt.size} segment(s) below hardware "
                f"timer floor of {timer_floor*1e9:.1f} ns "
                f"(worst: {worst*1e9:.3f} ns). The DDS timer cannot fire faster "
                f"than this.\n"
            )

        if not streaming:
            bad = dt < exec_floor - eps
            if np.any(bad):
                worst = float(dt[bad].min())
                idx = np.where(bad)[0]
                head = idx[:5].tolist()
                ellipsis = "..." if idx.size > 5 else ""
                raise ValueError(
                    f"[timing] K={K} tones require {n_cmd_seg} commands per "
                    f"segment, which take >= {exec_floor*1e9:.1f} ns to execute "
                    f"at 6.4 ns/cmd from the on-chip FIFO. "
                    f"{int(bad.sum())}/{dt.size} segment(s) violate this "
                    f"(worst: {worst*1e9:.2f} ns, segment indices "
                    f"{head}{ellipsis}). Either lengthen the trajectory, reduce "
                    f"K, or split tones across both channels.\n"
                )
            
        if streaming:
            bad = dt < stream_floor - eps
            if np.any(bad):
                worst = float(dt[bad].min())
                warnings.warn(
                    f"[timing] streaming mode needs >= {stream_floor*1e9:.0f} ns "
                    f"per segment (10 MHz sustained DMA refill for {n_cmd_seg} "
                    f"commands). {int(bad.sum())}/{dt.size} segment(s) are below "
                    f"this (worst: {worst*1e9:.2f} ns). The hardware FIFO will "
                    f"buffer short bursts but a long trajectory at this rate "
                    f"will underrun and glitch.\n",
                    UserWarning, stacklevel=2,
                )
        return 

    def _extend_trajectory(
        self,
        time_arr: np.ndarray,
        position_arr: np.ndarray,
        amplitudes,
        back_and_forth: bool,
        hold: float,
        where_hold_insert: Literal["after_return", "before_return"] = "before_return"
    ):
        def _append_hold(t, pos, amp, duration):
            t   = np.append(t, t[-1] + duration)
            pos = np.concatenate([pos, pos[:, -1:]], axis=1)
            if isinstance(amp, np.ndarray) and amp.ndim == 2:
                amp = np.concatenate([amp, amp[:, -1:]], axis=1)
            return t, pos, amp

        if not back_and_forth:
            if hold > 0:
                time_arr, position_arr, amplitudes = _append_hold(
                    time_arr, position_arr, amplitudes, hold)
        else:
            if hold > 0 and where_hold_insert == "before_return":
                time_arr, position_arr, amplitudes = _append_hold(
                    time_arr, position_arr, amplitudes, hold)

            dt_fwd  = np.diff(time_arr)
            t_back  = time_arr[-1] + np.cumsum(dt_fwd[::-1])
            time_arr     = np.concatenate([time_arr, t_back])
            position_arr = np.concatenate(
                [position_arr, position_arr[:, ::-1][:, 1:]], axis=1)
            if isinstance(amplitudes, np.ndarray) and amplitudes.ndim == 2:
                amplitudes = np.concatenate(
                    [amplitudes, amplitudes[:, ::-1][:, 1:]], axis=1)

            if hold > 0 and where_hold_insert == "after_return":
                time_arr, position_arr, amplitudes = _append_hold(
                    time_arr, position_arr, amplitudes, hold)

        return time_arr, position_arr, amplitudes

    def plan(
        self,
        time_arr: np.ndarray,
        position_arr: np.ndarray,
        channel: int = 0,
        amplitudes=None,
        back_and_forth: bool = False,
        hold: float = 0.0,
        where_hold_insert: Literal["after_return", "before_return"] = "before_return",
        skip_timing_check: bool = False,
    ):
        from dataclasses import dataclass

        @dataclass
        class MoveResult:
            time_arr:      np.ndarray
            position_arr:  np.ndarray
            freqs_kt:      np.ndarray
            amps_kt:       np.ndarray
            command_chain: list

        time_arr     = np.asarray(time_arr,     dtype=float)
        position_arr = np.asarray(position_arr, dtype=float)
        if position_arr.ndim == 1:
            position_arr = position_arr[np.newaxis, :]
        if position_arr.ndim != 2:
            raise ValueError("position_arr must be 1D or 2D (K, T).")

        if back_and_forth or hold > 0:
            time_arr, position_arr, amplitudes = self._extend_trajectory(
                time_arr, position_arr, amplitudes, back_and_forth, hold, where_hold_insert
            )

        K, T = position_arr.shape
        if time_arr.shape != (T,):
            raise ValueError(f"time_arr length ({time_arr.size}) must match position_arr last axis ({T}).")
        if T < 2:
            raise ValueError("Need at least two waypoints (T >= 2).")
        if not np.all(np.diff(time_arr) > 0):
            raise ValueError("time_arr must be strictly increasing.")

        tick_s = self.DDS_TIMER_MIN_NS * 1e-9
        ticks  = np.round(time_arr / tick_s).astype(np.int64)
        unique_ticks, _ = np.unique(ticks, return_index=True)

        if len(unique_ticks) < 2:
            raise ValueError("After quantizing to DDS clock, fewer than 2 distinct ticks remain.")

        if len(unique_ticks) < T:
            dropped = T - len(unique_ticks)
            warnings.warn(
                f"{dropped} waypoint(s) collapsed to duplicate clock ticks and were dropped. "
                f"{len(unique_ticks)} waypoints remain.",
                UserWarning, stacklevel=2,
            )
            q_time = unique_ticks * tick_s
            position_arr = np.stack([np.interp(q_time, time_arr, position_arr[k]) for k in range(K)])
            if isinstance(amplitudes, np.ndarray) and amplitudes.shape == (K, T):
                amplitudes = np.stack([np.interp(q_time, time_arr, amplitudes[k]) for k in range(K)])
            elif isinstance(amplitudes, np.ndarray) and amplitudes.shape == (T,):
                amplitudes = np.interp(q_time, time_arr, amplitudes)
            time_arr = q_time
            T = len(unique_ticks)
        else:
            time_arr = unique_ticks * tick_s

        core_indices = self._select_cores(channel, K)

        freqs_kt = convert_position_to_freq(
            position_arr, f_start_hz=self.f_start_hz, um_per_MHz=self.um_per_MHz
        )
        if np.any(freqs_kt < self.f_min_hz) or np.any(freqs_kt > self.f_max_hz):
            raise ValueError(
                f"Frequencies leave AOD band [{self.f_min_hz/1e6:.1f}, {self.f_max_hz/1e6:.1f}] MHz. "
                f"Got [{freqs_kt.min()/1e6:.3f}, {freqs_kt.max()/1e6:.3f}] MHz."
            )
        if np.any(freqs_kt > self.DDS_FREQ_NYQUIST_HZ):
            raise ValueError("Frequency above DDS Nyquist (625 MHz).")

        if amplitudes is None:
            amps_kt = np.full((K, T), self.max_total_amplitude / K)
        elif np.isscalar(amplitudes):
            assert isinstance(amplitudes, (int, float))
            amps_kt = np.full((K, T), float(amplitudes))
        else:
            amplitudes = np.asarray(amplitudes, dtype=float)
            if amplitudes.shape == (K,):
                amps_kt = np.tile(amplitudes[:, np.newaxis], (1, T))
            elif amplitudes.shape == (T,) and K == 1:
                amps_kt = amplitudes[np.newaxis, :]
            elif amplitudes.shape == (K, T):
                amps_kt = amplitudes
            else:
                raise ValueError(f"amplitudes shape {amplitudes.shape} invalid for K={K}, T={T}.")
        _tol = 1e-10
        if np.any(amps_kt < -_tol) or np.any(amps_kt > 1 + _tol):
            raise ValueError("amplitudes must lie in [0, 1].")
        amps_kt = np.clip(amps_kt, 0.0, 1.0)
        max_sum = float(amps_kt.sum(axis=0).max())
        if max_sum > self.max_total_amplitude:
            warnings.warn(
                f"max sum of tone amplitudes = {max_sum:.3f} exceeds "
                f"max_total_amplitude = {self.max_total_amplitude:.3f}.",
                UserWarning, stacklevel=2,
            )

        dt = np.diff(time_arr)
        if not skip_timing_check:
            self._check_segment_timing(dt, K, streaming=False)
        cmds = []

        cmds.append({"type": "trg_src", "src": "CARD"})
        for k in range(K):
            cmds.append({
                "type": "core_init", "core": core_indices[k],
                "freq_hz": float(freqs_kt[k, 0]), "amp": float(amps_kt[k, 0]),
                "phase": 0.0, "freq_slope_hz_s": 0.0, "amp_slope_per_s": 0.0,
            })
        cmds.append({"type": "exec_at_trg"})

        for i in range(T - 1):
            cmds.append({"type": "trg_timer", "dt_s": float(dt[i])})
            cmds.append({"type": "trg_src", "src": "TIMER"})
            for k in range(K):
                df = freqs_kt[k, i + 1] - freqs_kt[k, i]
                da = amps_kt[k, i + 1]  - amps_kt[k, i]
                cmds.append({
                    "type": "core_seg", "core": core_indices[k], "seg": i,
                    "freq_hz": float(freqs_kt[k, i]), "amp": float(amps_kt[k, i]),
                    "freq_slope_hz_s": float(df / dt[i]), "amp_slope_per_s": float(da / dt[i]),
                })
            cmds.append({"type": "exec_at_trg"})

        cmds.append({"type": "trg_src", "src": "CARD"})
        for k in range(K):
            cmds.append({
                "type": "core_park", "core": core_indices[k],
                "freq_hz": float(freqs_kt[k, -1]), "amp": float(amps_kt[k, -1]),
                "freq_slope_hz_s": 0.0, "amp_slope_per_s": 0.0,
            })
        cmds.append({"type": "exec_at_trg"})

        return MoveResult(
            time_arr=time_arr,
            position_arr=position_arr,
            freqs_kt=freqs_kt,
            amps_kt=amps_kt,
            command_chain=cmds,
        )

    def move(
        self,
        time_arr: np.ndarray,
        position_arr: np.ndarray,
        channel: int = 0,
        amplitudes = None,
        back_and_forth: bool = False,
        hold: float = 0.0,
        force_trigger: bool = False,
        continuous: bool = False,
        where_hold_insert: Literal["after_return", "before_return"] = "before_return",
        enter_replay_mode: bool = False,
        run_over_run_amplitude_modulation: np.ndarray | None = None,
    ) -> int:
        """
        Queue a synchronous K-tone move via DDS linear ramps starting on EXT0.

        Interpolates frequencies (via AOD calibration) between waypoints.

        Args:
            time_arr: (T,) ndarray (s). Increasing waypoint times.
            position_arr: (T,) or (K, T) ndarray (µm). Per-atom trajectory.
            channel: 0 (X-AOD) or 1 (Y-AOD).
            amplitudes: None, scalar, (K,), or (K, T) ndarray. Tone fractions.
            back_and_forth: Appends time-reversed position trajectory.
            hold: (s). Appends a zero-slope segment at the end.
            force_trigger: Starts immediately bypassing EXT0.
            continuous: Streams via background thread; retriggerable on EXT0.

        Returns:
            n_segments: Total linear ramp segments queued.
        """
        
        # there is also a bug: if you use amplitudes it doesn't handle the 1D array (only T not K,T) - just convert it from T to K,T
        # then of course also adapt this into plan function.
        # If you have time, also use the same skeleton for both, so when there is a patch incoming it automatically syncs both.

        # enter replay mode: This mode loads from the buffer and always refills itself with the same trajectory awaiting a new trigger
        # after having loaded once the into the buffer it will be independent of the computer and just keeps this trajectory.
        # I will also then need a new function that terminates the replay mode. 


        if self.card is None or self.dds is None:
            raise RuntimeError("Card not connected. Call connect() first.\n")

        if self.max_channel_amp_v == -np.inf:
            warnings.warn(
                "[AWGController] max_channel_amp_v is 0. Set a maximum output voltage before doing ANYTHING to prevent hardware damage."
            )
            _s = input("Do you still want to proceed? (y/n): ").strip().lower()
            if _s != 'y':
                print("Abort.\n")
                return 0
            print(
                f"Proceeding with max_channel_amp_v = {self.max_channel_amp_v} [V]. Be careful!\n"
            )

        # The run over run amplitude modulation allows to attenuate the output amplitude over a consecutive run of the same trajectory:
        # e.g. for some 0 < amp < 1 in amps run the trajectory, then load the next amp from amps. 
        # Where amps is the array: run_over_run_amplitude_modulation. 
        # I think the easiest is to multiply the max_total_amplitude with the values of the array and set that as the new max_total_amp
        # but keeping the old one in store so it is reset after one run of the trajectory. Of course this way then the maximum amplitude
        # that is set in the beginning is never exceeded.
        
        # ---- normalize array shapes -----------------------------------
        time_arr     = np.asarray(time_arr,     dtype=float)
        position_arr = np.asarray(position_arr, dtype=float)
        if position_arr.ndim == 1:
            position_arr = position_arr[np.newaxis, :]  # (1, T)
        if position_arr.ndim != 2:
            raise ValueError("position_arr must be 1D (single atom) or 2D (K, T). [K:=num of tones, T:=num of waypoints]\n")

        # ---- trajectory extension ------------------------------------
        if back_and_forth or hold > 0:
            time_arr, position_arr, amplitudes = self._extend_trajectory(
                time_arr, position_arr, amplitudes, back_and_forth, hold, where_hold_insert)

        K, T = position_arr.shape
        if time_arr.shape != (T,):
            raise ValueError(
                f"time_arr length ({time_arr.size}) must match position_arr "
                f"last axis ({T})."
            )
        if T < 2:
            raise ValueError("Need at least two waypoints (T >= 2).\n")
        if not np.all(np.diff(time_arr) > 0):
            raise ValueError("time_arr must be strictly increasing.\n")

        tick_s = self.DDS_TIMER_MIN_NS * 1e-9
        ticks = np.round(time_arr / tick_s).astype(np.int64)
        unique_ticks, _ = np.unique(ticks, return_index=True)

        if len(unique_ticks) < 2:
            raise ValueError(
                f"After quantizing to the DDS clock ({self.DDS_TIMER_MIN_NS} ns), "
                f"all waypoints collapse to fewer than 2 distinct ticks. "
                f"The total transport duration is too short.\n"
            )

        if len(unique_ticks) < T:
            dropped = T - len(unique_ticks)
            warnings.warn(
                f"{dropped} waypoint(s) collapsed to duplicate clock ticks and were dropped. "
                f"{len(unique_ticks)} waypoints remain.",
                UserWarning, stacklevel=2,
            )
            q_time = unique_ticks * tick_s
            position_arr = np.stack([
                np.interp(q_time, time_arr, position_arr[k]) for k in range(K)
            ])
            if isinstance(amplitudes, np.ndarray) and amplitudes.shape == (K, T):
                amplitudes = np.stack([
                    np.interp(q_time, time_arr, amplitudes[k]) for k in range(K)
                ])
            elif isinstance(amplitudes, np.ndarray) and amplitudes.shape == (T,):
                amplitudes = np.interp(q_time, time_arr, amplitudes)
            time_arr = q_time
            T = len(unique_ticks)
        else:
            time_arr = unique_ticks * tick_s

        # ---- core selection -------------------------------------------
        core_indices = self._select_cores(channel, K)

        # ---- position -> frequency + band check -----------------------
        freqs_kt = convert_position_to_freq(
            position_arr,
            f_start_hz=self.f_start_hz,
            um_per_MHz=self.um_per_MHz,
        )
        if np.any(freqs_kt < self.f_min_hz) or np.any(freqs_kt > self.f_max_hz):
            raise ValueError(
                f"Frequencies leave AOD band "
                f"[{self.f_min_hz/1e6:.1f}, {self.f_max_hz/1e6:.1f}] MHz. "
                f"Got [{freqs_kt.min()/1e6:.3f}, {freqs_kt.max()/1e6:.3f}] MHz.\n"
            )
        if np.any(freqs_kt > self.DDS_FREQ_NYQUIST_HZ):
            raise ValueError("Frequency above DDS Nyquist (625 MHz).\n")

        # ---- amplitude handling ---------------------------------------
        if amplitudes is None:
            amp_per_tone = self.max_total_amplitude / K
            amps_kt = np.full((K, T), amp_per_tone)
        elif np.isscalar(amplitudes):
            amps_kt = np.full((K, T), float(amplitudes)) # type:ignore
        else:
            amplitudes = np.asarray(amplitudes, dtype=float)
            if amplitudes.shape == (K,):
                amps_kt = np.tile(amplitudes[:, np.newaxis], (1, T))
            elif amplitudes.shape == (T,) and K == 1:
                amps_kt = amplitudes[np.newaxis, :]
            elif amplitudes.shape == (K, T):
                amps_kt = amplitudes
            else:
                raise ValueError(
                    f"amplitudes must be None, scalar, (K,), or (K, T). "
                    f"Got shape {amplitudes.shape} for K={K}, T={T}.\n"
                )
        _tol = 1e-10
        if np.any(amps_kt < -_tol) or np.any(amps_kt > 1 + _tol):
            raise ValueError("amplitudes must lie in [0, 1].\n")
        amps_kt = np.clip(amps_kt, 0.0, 1.0)
        max_sum = float(amps_kt.sum(axis=0).max())
        if max_sum > self.max_total_amplitude:
            warnings.warn(
                f"max sum of tone amplitudes = {max_sum:.3f} exceeds "
                f"max_total_amplitude = {self.max_total_amplitude:.3f}. "
                f"Risk of clipping on coherent phase alignments.\n"
            )

        dt = np.diff(time_arr)
        
        # ---- decide whether streaming is needed -----------------------
        n_cmds_est = self._estimate_n_commands(K, T)
        queue_cap  = self._queue_max_actual or self.SINGLE_MODE_QUEUE_MAX
        needs_streaming = continuous or (n_cmds_est > queue_cap)
        self._check_segment_timing(dt, K, streaming=needs_streaming)

        # ---- command counts per phase ---------------------------------
        n_init = 1 + 5 * K + 1   # CARD trg_src + K*(f,a,φ,df,da) + exec
        n_seg  = 2 + 4 * K + 1   # timer + TIMER trg_src + K*(f,a,df,da) + exec
        n_park = 2 + 4 * K + 1   # timer + TIMER trg_src + K*(f,a,df,da) + exec

        # ---- build the DDS command queue ------------------------------
        self.card.stop(spcm.M2CMD_CARD_STOP)
        self.dds.reset()
        cores = [self.dds[i] for i in core_indices]

        # Initial state: load t=0 values, wait for EXT0
        self.dds.trg_src(spcm.SPCM_DDS_TRG_SRC_CARD)
        for k, c in enumerate(cores):
            c.freq(float(freqs_kt[k, 0]) * units.Hz)
            c.amp(float(amps_kt[k, 0]))
            c.phase(0)
            c.freq_slope(0)
            c.amp_slope(0)
        self.dds.exec_at_trg()

        # Fill as many segments as fit in the FIFO on this initial push.
        # Reserve park budget only for single-shot mode.
        park_budget = n_park if not needs_streaming else 0
        segs_pushed = 0
        for i in range(T - 1):
            if n_init + (segs_pushed + 1) * n_seg + park_budget > queue_cap:
                break
            self.dds.trg_timer(float(dt[i]) * units.s)
            self.dds.trg_src(spcm.SPCM_DDS_TRG_SRC_TIMER)
            for k, c in enumerate(cores):
                df = freqs_kt[k, i + 1] - freqs_kt[k, i]
                da = amps_kt[k, i + 1]  - amps_kt[k, i]
                c.freq(float(freqs_kt[k, i]) * units.Hz)
                c.amp(float(amps_kt[k, i]))
                c.freq_slope(float(df / dt[i]) * (units.Hz / units.s))
                c.amp_slope(float(da / dt[i]) / units.s)
            self.dds.exec_at_trg()
            segs_pushed += 1

        # Single-shot and all segments fit: append park, done
        if not needs_streaming:
            self.dds.trg_timer(float(dt[-1]) * units.s)
            self.dds.trg_src(spcm.SPCM_DDS_TRG_SRC_TIMER)
            for k, c in enumerate(cores):
                c.freq(float(freqs_kt[k, -1]) * units.Hz)
                c.amp(float(amps_kt[k, -1]))
                c.freq_slope(0)
                c.amp_slope(0)
            self.dds.exec_at_trg()

        self.dds.write_to_card()

        # Arm the trigger engine
        flags = spcm.M2CMD_CARD_ENABLETRIGGER
        if force_trigger:
            flags |= spcm.M2CMD_CARD_FORCETRIGGER
        self.card.start(flags)

        # Launch streaming thread if trajectory overflows FIFO or continuous requested
        if needs_streaming:
            self._stream_freqs_kt   = freqs_kt
            self._stream_amps_kt    = amps_kt
            self._stream_dt_arr     = dt
            self._stream_cores      = cores
            self._stream_continuous = continuous
            self._stop_event        = threading.Event()
            self._stream_thread     = threading.Thread(
                target=self._stream_loop,
                args=(segs_pushed, T - 1),
                daemon=True,
            )
            self._stream_thread.start()

        print(
            f"[AODController] DDS armed: K={K} tones on CH{channel} "
            f"(cores {core_indices[0]}..{core_indices[-1]}), "
            f"{T-1} segments, {(time_arr[-1]-time_arr[0])*1e6:.2f} us total. "
            f"~{n_cmds_est}/{queue_cap} FIFO entries, "
            f"{'streaming' if needs_streaming else 'single-shot'}. "
            f"{'Force-triggered.' if force_trigger else 'Waiting for EXT0.'}\n"
        )
        return T - 1

    def _stream_loop(self, start_seg: int, total_segs: int) -> None:
        try:
            psutil.Process(os.getpid()).nice(psutil.REALTIME_PRIORITY_CLASS)
        except Exception:
            pass

        if self._stream_freqs_kt is None or self._stream_amps_kt is None \
                or self._stream_dt_arr is None or self._stream_cores is None:
            return

        K            = self._stream_freqs_kt.shape[0]
        cmds_per_seg = 2 + 4 * K + 1   # timer + TIMER trg_src + K*(f,a,df,da) + exec
        n_park_reinit = (2 + 4 * K + 1) + (1 + 5 * K + 1)  # park + re-init overhead
        seg_idx      = start_seg
        assert self._stop_event is not None, "_stop_event should have been set by move()"
        while not self._stop_event.is_set():
            if self.card is None or self.dds is None:
                break

            # Query available FIFO space (busy-wait: no sleep)
            try:
                if self._queue_max_actual is not None:
                    avail = self._queue_max_actual - int(self.card.get_i(spcm.SPC_DDS_QUEUE_CMD_COUNT))
                else:
                    total_c = int(self.dds.queue_cmd_max()) # trying to query again
                    current_queue = int(self.card.get_i(spcm.SPC_DDS_QUEUE_CMD_COUNT))
                    avail = total_c - current_queue
            except Exception as e:
                print(e)
                avail = cmds_per_seg  # conservative fallback: assume one slot free

            
            avail_for_segs = max(0, avail - n_park_reinit)
            segs_to_push = avail_for_segs // cmds_per_seg
            if segs_to_push == 0:
                time.sleep(0.001)
                continue  # FIFO full — keep polling

            built = 0
            hit_end = False
            while built < segs_to_push and not self._stop_event.is_set():
                if seg_idx >= total_segs:
                    hit_end = True
                    break

                i = seg_idx
                self.dds.trg_timer(float(self._stream_dt_arr[i]) * units.s)
                self.dds.trg_src(spcm.SPCM_DDS_TRG_SRC_TIMER)
                for k, c in enumerate(self._stream_cores):
                    df = self._stream_freqs_kt[k, i + 1] - self._stream_freqs_kt[k, i]
                    da = self._stream_amps_kt[k, i + 1]  - self._stream_amps_kt[k, i]
                    c.freq(float(self._stream_freqs_kt[k, i]) * units.Hz)
                    c.amp(float(self._stream_amps_kt[k, i]))
                    c.freq_slope(float(df / self._stream_dt_arr[i]) * (units.Hz / units.s))
                    c.amp_slope(float(da / self._stream_dt_arr[i]) / units.s)
                self.dds.exec_at_trg()
                built  += 1
                seg_idx += 1

            if built > 0:
                self.dds.write_to_card()  # flush segment batch first

            if hit_end:
                # Push timer-based park: fires dt[-1] after the last ramp completes
                self.dds.trg_timer(float(self._stream_dt_arr[-1]) * units.s)
                self.dds.trg_src(spcm.SPCM_DDS_TRG_SRC_TIMER)
                for k, c in enumerate(self._stream_cores):
                    c.freq(float(self._stream_freqs_kt[k, -1]) * units.Hz)
                    c.amp(float(self._stream_amps_kt[k, -1]))
                    c.freq_slope(0)
                    c.amp_slope(0)
                self.dds.exec_at_trg()

                if self._stream_continuous:
                    # Re-queue initial state: switch to CARD trigger and wait for EXT0.
                    # Flushed immediately and separately from the segment batch above
                    # to guarantee trg_src=CARD lands in the hardware FIFO with
                    # confirmed space (reserved via avail_for_segs above).
                    self.dds.trg_src(spcm.SPCM_DDS_TRG_SRC_CARD)
                    for k, c in enumerate(self._stream_cores):
                        c.freq(float(self._stream_freqs_kt[k, 0]) * units.Hz)
                        c.amp(float(self._stream_amps_kt[k, 0]))
                        c.phase(0)
                        c.freq_slope(0)
                        c.amp_slope(0)
                    self.dds.exec_at_trg()
                    self.dds.write_to_card()  # flush park+re-init as its own batch
                    seg_idx = 0   # restart trajectory on next EXT0
                else:
                    self.dds.write_to_card()
                    return        # single-shot: all segments queued, exit thread

        return


    def stop(self) -> None:
        if self._stop_event is not None:
            self._stop_event.set()
        if self._stream_thread is not None:
            self._stream_thread.join(timeout=5.0)
        self._stream_thread   = None
        self._stop_event      = None
        self._stream_freqs_kt = None
        self._stream_amps_kt  = None
        self._stream_dt_arr   = None
        self._stream_cores    = None

        if self.dds is not None and self.card is not None:
            self.card.stop(spcm.M2CMD_CARD_STOP)
            self.dds.reset()
            f_park = 0.5 * (self.f_min_hz + self.f_max_hz)
            for core in self.dds:
                core.amp(0)
                core.freq(f_park * units.Hz)
                core.freq_slope(0)
                core.amp_slope(0)
            self.dds.exec_at_trg()
            self.dds.write_to_card()
            self.card.start(spcm.M2CMD_CARD_ENABLETRIGGER,
                            spcm.M2CMD_CARD_FORCETRIGGER)
            time.sleep(0.01)
            self.card.stop()
        return
    
    def program_static(
        self,
        positions_um: np.ndarray,
        occupancy: np.ndarray,
        channel: int = 0,
        amplitudes: float | np.ndarray | None = None,
    ) -> np.ndarray:
        """
        Set DDS cores to static (non-moving) tones.

        Cores are assigned in ascending frequency order: the site with the lowest
        frequency gets core 0, the next gets core 1, and so on.
        Occupied sites get the given amplitude; empty sites get amplitude 0.

        Stores soft state in self._static_core_state[channel] for later use.

        Args:
            positions_um: (N,) trap positions [µm].
            occupancy:    (N,) bool — True where an atom is present.
            channel:      0 (X-AOD) or 1 (Y-AOD).
            amplitudes:   None → equal share of max_total_amplitude.
                          Scalar, (N,), or (n_active,) array.

        Returns:
            amps_set: (N,) amplitudes programmed, in the same order as positions_um.
        """
        if self.card is None or self.dds is None:
            raise RuntimeError("Card not connected. Call connect() first.")

        positions_um = np.asarray(positions_um, dtype=float)
        occupancy    = np.asarray(occupancy,    dtype=bool)
        N = len(positions_um)
        if len(occupancy) != N:
            raise ValueError("positions_um and occupancy must have the same length.")

        n_active     = int(occupancy.sum())
        core_indices = self._select_cores(channel, N)

        freqs = convert_position_to_freq(
            positions_um[np.newaxis, :],
            f_start_hz=self.f_start_hz,
            um_per_MHz=self.um_per_MHz,
        )[0]

        if np.any(freqs < self.f_min_hz) or np.any(freqs > self.f_max_hz):
            raise ValueError(
                f"Frequencies outside AOD band "
                f"[{self.f_min_hz/1e6:.1f}, {self.f_max_hz/1e6:.1f}] MHz. "
                f"Got [{freqs.min()/1e6:.3f}, {freqs.max()/1e6:.3f}] MHz."
            )

        if amplitudes is None:
            amp_per = self.max_total_amplitude / max(n_active, 1)
            amps_set = np.where(occupancy, amp_per, 0.0)
        elif np.isscalar(amplitudes):
            amps_set = np.where(occupancy, float(amplitudes), 0.0)
        else:
            amplitudes = np.asarray(amplitudes, dtype=float)
            if amplitudes.shape == (N,):
                amps_set = np.where(occupancy, amplitudes, 0.0)
            elif amplitudes.shape == (n_active,):
                full_amp = np.zeros(N)
                full_amp[occupancy] = amplitudes
                amps_set = full_amp
            else:
                raise ValueError(
                    f"amplitudes shape {amplitudes.shape} invalid for N={N}, n_active={n_active}."
                )

        # Assign cores in ascending frequency order
        sort_order = np.argsort(freqs)

        self.card.stop(spcm.M2CMD_CARD_STOP)
        self.dds.reset()
        self.dds.trg_src(spcm.SPCM_DDS_TRG_SRC_CARD)
        for rank, si in enumerate(sort_order):
            core = self.dds[core_indices[rank]]
            core.freq(float(freqs[si]) * units.Hz)
            core.amp(float(amps_set[si]))
            core.phase(0)
            core.freq_slope(0)
            core.amp_slope(0)
        self.dds.exec_at_trg()
        self.dds.write_to_card()
        self.card.start(spcm.M2CMD_CARD_ENABLETRIGGER, spcm.M2CMD_CARD_FORCETRIGGER)

        self._static_core_state[channel] = {
            'positions_um': positions_um.copy(),
            'freqs_hz':     freqs.copy(),
            'amps':         amps_set.copy(),
            'occupancy':    occupancy.copy(),
            'sort_order':   sort_order.copy(),
            'core_indices': list(core_indices),
        }

        print(
            f"[AWGController] Static tones: {n_active}/{N} occupied, CH{channel}, "
            f"cores {core_indices[0]}..{core_indices[-1]}.\n"
        )
        return amps_set

    def tones_on_grid(self, f0_req = 100e6, df_req = 1e6, n_tones = 20):
        assert self.card is not None, "Card not connected. Call connect() first.\n"
        f_step = self.card.get_d(spcm.SPC_DDS_AVAIL_FREQ_STEP)

        print(f"f_step, {f_step}")

        n0 = round(f0_req / f_step)
        dn = round(df_req / f_step)

        f0 = n0 * f_step
        df = dn * f_step

        freqs = [f0 + k * df for k in range(n_tones)]

        return freqs


